name: Publish cli release
on:
  workflow_call:
    inputs:
      os:
        type: string
        description: The OS to compile the binary for
      tag:
        type: string
        description: The tag to use for the release
permissions:
  contents: write

jobs:
  release:
    name: Release version ${{ github.event.release.tag_name}} on ${{ inputs.os }}
    runs-on: ${{ inputs.os }}
    concurrency: release-${{ inputs.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Download Python dependencies
        run: pip install -r requirements.txt
      - name: Compile the binary
        run: pyinstaller webexp.py --onefile
      # macOS Apple Silicon (arm64)
      - if: inputs.os == 'macos-latest'
        run: mv dist/webexp dist/webexp-darwin-arm64
      - uses: softprops/action-gh-release@v2
        if: inputs.os == 'macos-latest'
        with:
          tag_name: ${{ inputs.tag }}
          files: dist/webexp-darwin-arm64

      # macOS Intel (x86_64)
      - if: inputs.os == 'macos-13'
        run: mv dist/webexp dist/webexp-darwin-amd64
      - uses: softprops/action-gh-release@v2
        if: inputs.os == 'macos-13'
        with:
          tag_name: ${{ inputs.tag }}
          files: dist/webexp-darwin-amd64
      # Ubuntu
      - if: inputs.os == 'ubuntu-latest'
        run: mv dist/webexp dist/webexp-linux
      - uses: softprops/action-gh-release@v2
        if: inputs.os == 'ubuntu-latest'
        with:
          tag_name: ${{ inputs.tag }}
          files: dist/webexp-linux
