name: Publish cli binaries in release
on:
  release:
    types:
      - published
permissions:
  contents: write

jobs:
  build-and-release:
    name: Release version ${{ github.event.release.tag_name}} on ${{ matrix.runner-os }}
    strategy:
      fail-fast: false
      matrix:
        runner-os: [windows-latest, ubuntu-latest, macos-latest, macos-13]
    uses: ./.github/workflows/compile-source.yaml
    secrets: inherit
    with:
      os: ${{ matrix.runner-os }}
      tag: ${{ github.event.release.tag_name }}
